version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: examples/demo/Dockerfile
    ports:
      - "8080:8080" # URL Shortener API
      - "2112:2112" # Metrics Endpoint
    volumes:
      - ./pastaay.yaml:/root/pastaay.yaml
    depends_on:
      - db # Wait for database to start

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=pastaay
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=shortener
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./examples/demo/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus