services:
  app:
    build:
      context: ../../
      dockerfile: examples/demo/Dockerfile
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 1024M
    ports:
      - "8080:8080"
      - "2112:2112"
    environment:
      - CONFIG_PATH=/root/config/pastaay.yaml
      - REDIS_ADDR=redis:6379
      - DB_DSN=postgres://pastaay:secret@db:5432/shortener?sslmode=disable
      - MONGO_URI=mongodb://mongo:27017
      - KAFKA_ADDR=redpanda:9092
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    volumes:
      - ./:/root/config/
    depends_on:
      - db
      - redis
      - mongo
      - redpanda
      - rabbitmq
      - otel-collector

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=pastaay
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=shortener
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --smp 1
      - --reserve-memory 0M
      - --overprovisioned
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"

  otel-collector:
    image: otel/opentelemetry-collector:0.96.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger Web UI
      - "4317"        # OTLP gRPC