services:
  app:
    build:
      context: .
      dockerfile: examples/demo/Dockerfile
      network: host
    ports:
      - "8080:8080"
      - "2112:2112"
    environment:
      - REDIS_ADDR=redis:6379
      - DB_DSN=postgres://pastaay:secret@db:5432/shortener?sslmode=disable
      - MONGO_URI=mongodb://mongo:27017
    volumes:
      - ./examples/demo/pastaay.yaml:/root/pastaay.yaml
    depends_on:
      - db
      - redis
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=pastaay
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=shortener
    ports:
      - "5433:5432"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./examples/demo/prometheus.yml:/etc/prometheus/prometheus.yml