apiVersion: chaos.pastaay.io/v1
kind: ChaosPolicy
metadata:
  name: prod-db-resilience-test
  namespace: pastaay-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: "sql"
  target: "database"
  errorChance: 0.15   # %15 Error Rate
  duration: "45s"     # Auto-Rollback
  errorBody: "GitOps Automated Chaos Strike"